version: '3.8'

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lattis
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-development-secret
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lattis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  test:
    build:
      context: .
      target: deps
    command: npm test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db_test:5432/test_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=test-secret
    depends_on:
      - db_test

  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  e2e:
    build:
      context: .
      target: deps
    command: npm run test:e2e
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db_test:5432/test_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=test-secret
    depends_on:
      - db_test

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: 